baseURL = "https://rayed.com/"
languageCode = "en-us"
title = "Rayed's Real Life"
theme = "ananke"
disqusShortname = "rayed"

sectionPagesMenu = "main"

[[menu.main]]
    name = "Old Blog"
    weight = -110
    url = "https://rayed.com/old_wordpress/"


[params]
    github = "https://github.com/rayed"
    twitter = "https://twitter.com/rayed"
    instagram = "https://www.instagram.com/rayed/"
    linkedin = "https://www.linkedin.com/in/rayed/"
    featured_image = "/static/1500x500.jpeg"
